const GET_MNEMONIC: string = 'GET_MNEMONIC';
const CREATE_WALLET: string = 'CREATE_WALLET';
const GENERATE_MNEMONIC_PHRASE: string = 'GENERATE_MNEMONIC_PHRASE';
const VALIDATE_MNEMONIC_DATA: string = 'VALIDATE_MNEMONIC_DATA';
const SIGN_TRANSACTION: string = 'SIGN_TRANSACTION';
const SET_TO_ADDRESS: string = 'SET_TO_ADDRESS';
const SET_TRANSFER_TOKEN: string = 'SET_TRANSFER_TOKEN';
const SET_TRANSFER_AMOUNT: string = 'SET_TRANSFER_AMOUNT';

export {
  GET_MNEMONIC,
  CREATE_WALLET,
  GENERATE_MNEMONIC_PHRASE,
  VALIDATE_MNEMONIC_DATA,
  SIGN_TRANSACTION,
  SET_TO_ADDRESS,
  SET_TRANSFER_TOKEN,
  SET_TRANSFER_AMOUNT,
};
