const INIT_WEB3: string = 'INIT_WEB3'
const CREATE_TOKEN: string = 'CREATE_TOKEN'
const MINT_TOKEN: string = 'MINT_TOKEN'
const TRANSFER_TOKEN: string = 'TRANSFER_TOKEN'
const GET_ALL_TOKEN: string = 'GET_ALL_TOKEN'
const GET_TOKEN_DETAIL: string = 'GET_TOKEN_DETAIL'
const GET_TOKEN_BALANCE: string = 'GET_TOKEN_BALANCE'

export { INIT_WEB3, MINT_TOKEN, TRANSFER_TOKEN, CREATE_TOKEN, GET_ALL_TOKEN, GET_TOKEN_DETAIL, GET_TOKEN_BALANCE }